CMakeLists.txt for our tests: fixing gtest related linker error:
undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5' due to:

    gtest-port.h:1767:    DeleteThreadLocalValue(pthread_getspecific(key_));
    gtest-port.h:1804:    static_cast<ThreadLocalValueHolderBase*>(pthread_getspecific(key_));